baseURL = "/"
languageCode = "en-us"
title = "编程中学"
theme = ["docsy"]
description = "基于Jupyter编程环境的编程学习平台，无需安装软件、打开网站就能学，适合12岁以上编程爱好者"
Paginate = 20

# SEO
enableRobotsTXT = true

# Docsy: Gives values to .Lastmod etc.
enableGitInfo = true

# Docsy: Language settings
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Docsy: Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Docsy: Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

 # Docsy: First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Top-level navigation (horizontal)

[[menu.main]]
    name = "首页"
    weight = -104
    url = "/"

[[menu.main]]
    name = "开始学习"
    weight = -103
    url = "/docs/courses/"
[[menu.main]]
    name = "申请正式账号"
    weight = -98
    url = "/docs/apply-account/"
[[menu.main]]
    name = "Jupyter编程环境"
    weight = -97
    url = "/docs/jupyter/"


# Docsy: Configure the format of URLs per section.
#[permalinks]
#blog = "/:section/:year/:month/:day/:slug/"

## Docsy: Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Docsy: Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
id = "UA-135379910-1"

# Docsy: Language configuration

[languages]
[languages.en]
title = "编程中学"
description = "基于Jupyter编程环境的编程学习平台，无需安装软件、打开网站就能学，适合12岁以上编程爱好者"
languageName ="中文"
weight = 1
# Example of another language: Norwegian
#[languages.no]
#title = "Docsy"
#description = "Docsy er operativsystem for skyen"
#languageName ="Norsk"
#contentDir = "content/no"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"

# Site params

[params]
github_repo = "https://github.com/matgek/learnincode-website-kubeflow"
RSSLink = "/index.xml"
author = "编程中学" # add your company name
github = "kubeflow" # add your github profile name
twitter = "kubeflow" # add your twitter profile
#email = "myemail@myaddress.xxx"

copyright = "编程中学"
privacy_policy = "https://policies.google.com/privacy"

# Docsy: Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "007239566369470735695:624rglujm-w"

version = "GitHub"
githubbranch = "master"

# Add new release versions here
[[params.versions]]
  version = "learn-in-code"
  githubbranch = "master"
  url = "https://github.com/learn-in-code"

#[[params.versions]]
#  version = "v0.2"
#  githubbranch = "v0.2-branch"
#  url = "https://v0-2.kubeflow.org"

# Docsy: User interface configuration
[params.ui]
# Docsy: Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Docsy: Disable the search box in the side bar.
sidebar_search_disable = true
#  Docsy: Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/kubeflow/website/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/kubeflow/website/issues/new">tell us how we can improve</a>.'


#[params.links]
# Docsy: "User" links will show on left side of footer and in the community page if you have one.
#[[params.links.user]]
#	name ="Twitter"
#	url = "https://twitter.com/kubeflow"
#	icon = "fab fa-twitter"
#        desc = "Follow us on Twitter to get the latest news"
#[[params.links.user]]
#	name = "GitHub"
#	url = "https://github.com/kubeflow/kubeflow"
#	icon = "fab fa-github"

# Docsy: "Developer" links will show on right side of footer and in the community page if you have one.
#[[params.links.developer]]
#	name = "A name"
#	url = "http://example.com"
#	icon = "fab fa-envelope"
#       desc = "A description"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "azure-deploy"
URL = "azblob://$web"
